import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export function useLanguage() {
  return useContext(LanguageContext);
}

const translations = {
  en: {
    brand_name: 'TASKFLOW',
    // Nav
    nav_dashboard: 'DASHBOARD',
    nav_team: 'TEAM',
    nav_directives: 'DIRECTIVES',
    nav_create_task: 'CREATE TASK',
    nav_all_tasks: 'ALL TASKS',
    nav_all_users: 'ALL USERS',
    nav_departments: 'DEPARTMENTS',
    nav_analytics: 'ANALYTICS',
    nav_logout: 'LOGOUT',
    nav_overview: 'OVERVIEW',
    user_mgmt_tab: 'USER MANAGEMENT',
    nav_features: 'FEATURES',
    nav_benefits: 'BENEFITS',
    nav_sys_status: 'SYSTEM STATUS',
    nav_privacy: 'PRIVACY',
    nav_terms: 'TERMS',
    
    // Dashboard / Titles
    title_manager_hub: 'MANAGER HUB',
    title_control_center: 'CONTROL CENTER',
    title_my_tasks: 'MY TASKS',
    title_overview: 'OVERVIEW',
    system_control: 'SYSTEM CONTROL',
    root_access: 'ROOT ACCESS AUTHORIZED',
    global_metrics: 'GLOBAL METRICS, USER MANAGEMENT, AND DEPARTMENT CONTROL',
    landing_hero_title: 'Superlative execution for ',
    landing_hero_highlight: 'elite organizations.',
    landing_hero_subtitle: 'Transform scattered communication into a streamlined, high-velocity task lifecycle management system.',
    landing_signin_btn: 'Sign in to Workspace',
    landing_docs_btn: 'View Documentation',
    feature_title: 'Engineered with Precision',
    feature_subtitle: 'Every feature built to remove friction from your workflow.',
    access_workspace: 'ACCESS WORKSPACE',
    sys_ops_os: 'Enterprise Operations OS v2.4',
    
    // Stats
    stat_active: 'ACTIVE',
    stat_pending: 'PENDING',
    stat_completed: 'COMPLETED',
    stat_overdue: 'OVERDUE',
    stat_total_tasks: 'TOTAL TASKS',
    stat_active_cycles: 'ACTIVE CYCLES',
    stat_pending_queue: 'PENDING QUEUE',
    stat_critical_overdue: 'CRITICAL OVERDUE',
    stat_total: 'TOTAL',
    
    // Task Card & Tables
    task_priority: 'PRIORITY',
    task_status: 'STATUS',
    task_due_date: 'DUE DATE',
    task_assigned_to: 'ASSIGNED TO',
    task_department: 'DEPARTMENT',
    task_edit: 'EDIT',
    task_transfer: 'TRANSFER',
    task_directive_label: 'TASK DIRECTIVE',
    assignee_label: 'ASSIGNEE',
    level_label: 'LEVEL',
    actions_label: 'ACTIONS',
    records_label: 'RECORDS',
    user_label: 'USER',
    role_label: 'ROLE',
    nav_status: 'STATUS',
    
    // Priorities
    priority_low: 'LOW',
    priority_med: 'MEDIUM',
    priority_high: 'HIGH',
    
    // Statuses
    status_pending: 'PENDING',
    status_active: 'IN PROGRESS',
    status_done: 'COMPLETED',
    online_status: 'ONLINE',
    revoked_status: 'REVOKED',
    
    // Common Buttons
    btn_cancel: 'CANCEL',
    btn_create: 'CREATE',
    btn_assign: 'ASSIGN',
    btn_reset: 'RESET',
    btn_delete: 'DELETE',
    btn_confirm: 'CONFIRM',
    btn_abort: 'ABORT',
    btn_proceed: 'PROCEED',
    btn_save: 'SAVE CHANGES',
    btn_revoke: 'REVOKE',
    btn_grant: 'GRANT',
    btn_view_tasks: 'VIEW TASKS',
    btn_transfer: 'TRANSFER',
    btn_add_employee: 'ADD EMPLOYEE',
    btn_deploy_task: 'DEPLOY TASK',
    btn_initiate: 'INITIATE',
    btn_initialize: 'INITIALIZE CONNECTION',
    btn_login: 'LOGIN',
    btn_create_user: 'CREATE USER',
    btn_assign_task: 'ASSIGN TASK',
    btn_transmit: 'TRANSMIT',
    btn_purge: 'PURGE TASK',
    btn_update: 'UPDATING...',
    btn_creating: 'CREATING...',
    
    // Placeholders & Search
    ph_search_name: 'Search by name or email...',
    ph_enter_dept: 'Enter department name...',
    ph_task_title: 'Task title...',
    ph_task_desc: 'Mission details...',
    ph_full_name: 'Full Name',
    ph_email: 'Email address',
    ph_password: 'Password',
    ph_new_password: 'New password',
    ph_confirm_password: 'Confirm password',
    ph_search_directives: 'Search directives...',
    ph_mission_details: 'Mission details...',
    ph_sys_update: 'System Update...',
    ph_search_user: 'Search user...',
    ph_brief_description: 'Brief description (optional)',
    ph_select_manager: 'Select Manager...',
    ph_select_dept: 'Select Department...',
    ph_admin_token: 'Required for terminal access',
    
    // Messages & Alerts
    msg_loading: 'LOADING...',
    msg_no_tasks: 'NO DIRECTIVES FOUND',
    msg_no_tasks_found: 'No tasks found',
    msg_tasks_appear_here: 'Tasks will appear here.',
    msg_task_update_success: 'Task marked as {status}',
    msg_task_updated: 'Task updated successfully',
    msg_failed_update: 'Failed to update task',
    msg_title_required: 'Title is required',
    msg_assignee_required: 'Assignee is required',
    msg_no_users: 'NO USERS FOUND',
    msg_no_notifs: 'No notifications yet.',
    msg_no_results: 'NO MATCHING RECORDS',
    msg_updating: 'UPDATING...',
    overdue_alert: 'OVERDUE ALERT',
    mission_progress: 'MISSION PROGRESS',
    all_tasks_on_schedule: 'ALL TASKS ON SCHEDULE',
    overdue_tasks_alert: 'OVERDUE TASKS REQUIRE IMMEDIATE ATTENTION',
    msg_unassigned: 'Unassigned',
    msg_no_employees_found: 'No employees found',
    msg_no_employees_desc: 'Try another name or email, or add a new employee.',
    
    // Departments
    dept_hr: 'HR',
    dept_it: 'IT',
    dept_sales: 'Sales',
    dept_design: 'Design',
    dept_marketing: 'Marketing',
    dept_development: 'Development',
    dept_comp_rates: 'DEPARTMENT COMPLETION RATES',
    create_dept_title: 'CREATE DEPARTMENT',
    active_depts: 'ACTIVE DEPARTMENTS',
    all_depts_filter: 'ALL DEPARTMENTS',
    
    // Roles
    role_manager: 'Manager',
    role_employee: 'Employee',
    role_admin: 'Admin',
    label_managers: 'MANAGERS',
    label_employees: 'EMPLOYEES',
    label_admins: 'ADMINS',
    role_selector_title: 'SELECT ROLE',
    
    // Manager Specific
    all_depts: 'ALL DEPARTMENTS',
    cross_dept_cmd: 'CROSS-DEPARTMENT COMMAND',
    dept_mgr_dir: 'Department manager directory',
    cmd_roster: 'command roster',
    hide_tfr_list: 'HIDE TRANSFER LIST',
    open_tfr_list: 'OPEN TRANSFER LIST',
    tfr_task_ready: 'transferable tasks ready',
    tfr_incoming: 'INCOMING',
    tfr_sent: 'SENT',
    tfr_task_list: 'TRANSFER TASK LIST',
    tfr_directives: 'Transferred directives',
    tfr_from: 'From Manager',
    tfr_to: 'To Manager',
    tfr_timestamp: 'Transferred',
    target_dept: 'TARGET DEPARTMENT',
    target_manager: 'TARGET MANAGER',
    receiving_manager: 'Receiving Manager',
    
    // Admin Specific
    title_create_user: 'CREATE NEW USER',
    title_assign_task: 'ASSIGN NEW TASK',
    title_reset_password: 'RESET USER PASSWORD',
    title_delete_dept: 'DELETE DEPARTMENT?',
    title_sys_auth: 'SYSTEM AUTHORIZATION REQUIRED',
    auth_final: 'Final Authorization',
    detected_conflicts: 'DETECTED CONFLICTS',
    irrevocable_action: 'CRITICAL: This action is irreversible.',
    label_users: 'USERS',
    label_active_count: 'ACTIVE',
    dept_workload: 'STACKED DEPARTMENT WORKLOAD',
    status_split: 'GLOBAL STATUS SPLIT',
    
    // Login & Onboarding
    identify_clearance: 'IDENTIFY LOGIN CLEARANCE',
    sector_command: 'Sector Command',
    workspace_access: 'Workspace Access',
    op_terminal_login: 'OPERATIONAL TERMINAL LOGIN',
    onboarding_title: 'Secure Onboarding',
    onboarding_subtitle: 'ACTIVATION',
    set_passphrase: 'Set Secure Passphrase',
    activate_btn: 'ACTIVATE ACCOUNT',
    account_activated: 'ACCOUNT ACTIVATED',
    login_proceed: 'PROCEED TO LOGIN',
    val_invite: 'VALIDATING SECURE INVITE LINK...',
    link_expired: 'LINK EXPIRED',
    already_activated: 'ALREADY ACTIVATED',
    onboarding_footer: 'THIS IS A ONE-TIME SECURE ACTIVATION LINK. DO NOT SHARE WITH UNAUTHORIZED PERSONNEL.',
    login_email: 'Email',
    login_password: 'Password',
    back_to_root: 'Back to Root',
    initiate_btn: 'Initiate',
    admin_workspace: 'Admin Workspace',
    manager_workspace: 'Manager Workspace',
    employee_workspace: 'Employee Workspace',
    sys_decrypt_token: 'System Decrypt Token',
    auth_prohibited: 'UNAUTHORIZED ACCESS IS STRICTLY PROHIBITED.',
    auth_logged: 'ALL OPERATIONS ARE LOGGED.',
    init_conn_btn: 'LOGIN',
    
    // Signup
    title_create_account: 'Create account',
    subtitle_join_today: 'Join Taskflow today',
    label_full_name: 'Full Name',
    ph_john_doe: 'John Doe',
    ph_example_email: 'you@example.com',
    msg_already_have_account: 'Already have an account?',
    link_signin: 'Sign in',
    btn_create_account: 'Create Account',
    
    // Feature Details
    feature_1_title: 'Military-Grade Access Control',
    feature_1_desc: 'No public signup. Strict hierarchical provisioning through managed invite-only growth.',
    feature_2_title: 'Real-time Synchronization',
    feature_2_desc: 'Powered by WebSockets. Instant task deployment, status updates, and live toasts the millisecond a manager assigns an objective.',
    feature_3_title: 'Automated Lifecycle',
    feature_3_desc: 'Autonomous database cleanup routines purge completed tasks older than 30 days, keeping your storage pristine and query speeds blazing fast.',
    feature_4_title: 'Sector Segregation',
    feature_4_desc: 'JSON-based dynamic department routing.',
    
    // Testimonials & Footer
    trusted_by: 'Trusted by velocity-obsessed teams.',
    testimonial_1_text: "Taskflow eliminated our reliance on 5 different tools. The structural rigidity actually made us move 3x faster.",
    testimonial_1_author: "Sarah Jenkins",
    testimonial_1_role: "VP Engineering, NexusTech",
    testimonial_2_text: "The cleanest UI I've ever seen for project management. It feels like an extension of my brain.",
    testimonial_2_author: "Marcus Thorne",
    testimonial_2_role: "Product Lead, Synthetix",
    testimonial_3_text: "We needed strict hierarchical control without the clunky interface. This delivered perfectly.",
    testimonial_3_author: "Elena Rodriguez",
    testimonial_3_role: "Operations Director, VoidCorp",
    cta_title: 'Ready to evolve your workflow?',
    cta_subtitle: 'Access is restricted to invited personnel.',
    cta_btn: 'ENTER TASKFLOW',
    footer_rights: '© 2026 TASKFLOW SYSTEMS INC. ALL RIGHTS RESERVED.',
    tag_overdue: 'OVERDUE',
    tag_due: 'DUE',
    tag_left: 'LEFT',
    tag_ovr: 'OVR',
    tooltip_edit: 'Edit Directive',
    task_transfer_btn: 'TRANSFER',
    activated_desc: 'Your account has been successfully initialized. You can now access the operational terminal.',
    go_to_login: 'GO TO LOGIN',
    val_invite_err: 'Invalid or expired invite link.',
    activate_err: 'Failed to activate account.',
    invalid_invite: 'Invalid or expired invite.',
    access_denied: 'ACCESS DENIED',
    passphrase_min_len: 'Passphrase must be at least 6 characters.',
    passphrase_mismatch: 'Passwords do not match.',
    
    // Error States
    err_failed_depts: 'Failed to load departments',
    err_failed_users: 'Failed to load users',
    err_failed_history: 'Failed to retrieve user task history.',
    err_pass_mismatch: 'Passwords do not match.',
    err_pass_short: 'Passphrase must be at least 6 characters.',
    err_name_req: 'Department name is required.',
    err_select_manager: 'Select a manager for the employee',
    msg_tfr_params_err: 'Select a task, department, and manager for transfer.',

    // Additional Dashboard Keys
    dept_mgr_desc: 'View each department manager and hand off a directive to another manager.',
    loading_mgr_net: 'Loading department manager network...',
    label_department: 'DEPARTMENT',
    label_transferred: 'Transferred',
    msg_no_mgr_mapping: 'No department manager mapping available.',
    msg_tfr_desc: 'Tasks transferred between managers appear here with source and destination manager details.',
    label_tfr_record: 'transfer record',
    label_tfr_records: 'transfer records',
    label_assigned_ems: 'Assigned employees',
    label_assigned_ems_desc: 'Only employees assigned to your account are shown here.',
    ph_search_ems: 'Search employees by name or email...',
    btn_add_emp: 'Add Employee',
    label_total_emp: 'total employee',
    label_total_emps: 'total employees',
    label_visible: 'visible',
    btn_disable_emp: 'Disable Employee',
    btn_enable_emp: 'Enable Employee',
    msg_no_ems_found: 'No employees found',
    msg_no_ems_found_desc: 'Try another name or email, or add a new employee.',
    msg_no_tasks_criteria: 'NO DIRECTIVES MATCHING CURRENT CRITERIA',
    label_records_caps: 'RECORDS',
    msg_no_tasks_dept: 'NO DIRECTIVES IN THIS DEPARTMENT',
    label_regional_cmd: 'REGIONAL COMMAND AUTHORIZED',
    label_mgr_overview: 'MANAGER OVERVIEW',
    msg_managing_intro: 'You are managing',
    msg_managing_dept: 'department',
    msg_managing_depts: 'departments',
    label_managing_depts: 'MANAGING DEPARTMENTS',
    btn_deploy_task_caps: 'DEPLOY TASK',
    tab_overview: 'OVERVIEW',
    tab_team: 'TEAM',
    tab_tasks: 'TASKS',

    // Modals & Forms
    title_deploy_directive: 'DEPLOY NEW DIRECTIVE',
    title_edit_directive: 'EDIT TASK DIRECTIVE',
    label_directive_desig: '// DIRECTIVE DESIGNATION',
    ph_example_directive: 'e.g. Initialize Subsystem Alpha',
    label_parameters_opt: '// PARAMETERS (OPTIONAL)',
    label_assign_emp: '// ASSIGN EMPLOYEE',
    ph_search_name_email: 'Search name or email',
    label_target_dept: '// TARGET DEPARTMENT',
    label_start_cycle: '// START CYCLE',
    label_deadline_cycle: '// DEADLINE CYCLE',
    label_priority_level: '// PRIORITY LEVEL',
    btn_transmit_caps: '⚡ TRANSMIT',
    title_create_emp: 'CREATE NEW EMPLOYEE',
    label_full_name_caps: '// FULL NAME',
    label_email_caps: '// EMAIL',
    label_password_caps: '// PASSWORD',
    ph_min_6_char: 'Min 6 characters',
    label_assign_dept_caps: '// ASSIGN DEPARTMENT',
    msg_select_dept_err: '⚠ Select a department',
    btn_create_emp_caps: '⚡ CREATE EMPLOYEE',
    title_tfr_directive: 'TRANSFER DIRECTIVE TO MANAGER',
    label_selected_task: 'Selected Task',
    msg_select_task_queue: 'Select a task from your queue',
    msg_curr_dept_status: 'Current department: {dept} | Current status: {status}',
    msg_tfr_instruction: 'Choose a directive that should move to another department manager.',
    msg_no_tfr_ready: 'No transfer-ready tasks were found in your queue right now. Only tasks currently owned by you inside your managed departments can be transferred.',
    msg_no_mgr_avail: 'No other active manager is available for transfer at the moment. Add another active manager to a department to move this task.',
    label_choose_task: '// CHOOSE TASK',
    ph_select_task: '-- SELECT TASK --',
    label_target_mgr: '// TARGET MANAGER',
    ph_select_mgr: '-- SELECT MANAGER --',
    msg_no_mgr_dept: 'No other active manager is available inside the selected department.',
    label_receiving_mgr: 'Receiving Manager',
    label_depts_list: 'Departments:',
    btn_transfer_caps: 'TRANSFER TASK',
    btn_transferring: 'TRANSFERRING...',

    // Admin Specific
    title_user_tasks: '// ASSIGNED TASKS',
    msg_no_tasks_assigned: 'No Tasks Assigned',
    label_due: 'Due:',
    label_user_role: '// SELECT ROLE',
    label_assign_mgr: '// ASSIGN MANAGER',
    ph_search_role_email: 'Search by name or email',
    label_task_title: '// TASK TITLE',
    ph_task_title_placeholder: 'Task title',
    label_priority: '// PRIORITY',
    label_target_user: 'TARGET USER',
    msg_reset_pass_desc: 'Existing password is never shown. Only a new password can be set.',
    ph_reenter_pass: 'Re-enter new password',
    label_conflicts: '// DETECTED CONFLICTS:',
    label_emp_accounts: 'employee account(s)',
    label_mgr_accounts: 'manager account(s)',
    label_active_tasks: 'active task(s)',
    btn_bypass_delete: 'BYPASS & DELETE',
    btn_confirm_delete: 'CONFIRM DELETE',

    // Greetings & Alerts
    welcome_back: 'WELCOME BACK',
    hello: 'HELLO',
    sys_date: 'SYS_DATE',
    all_priorities: 'ALL PRIORITIES',
    critical_overdue: 'CRITICAL OVERDUE',
    today_due: 'TODAY DUE',
    upcoming_queued: 'UPCOMING QUEUED',
    completed_editable: 'COMPLETED (EDITABLE)',

    // Notifications
    notif_log: 'NOTIFICATION LOG',
    task_alerts: 'TASK ALERTS',
    mark_read: 'MARK ALL AS READ',
    just_now: 'JUST NOW',

    // Sidebar & Badges
    badge_employee: 'EMPLOYEE',
    badge_manager: 'MANAGER',
    badge_admin: 'ADMIN',
    label_cyber_edition: 'CYBER EDITION',
    label_dept_manager_caps: 'DEPARTMENT MANAGER',
    label_dept_manager: 'Department Manager',
    label_operator: 'Operator',
    unassigned_caps: 'UNASSIGNED',
    all_statuses: 'ALL STATUSES',
    all_employees: 'ALL EMPLOYEES',
    you: 'YOU',
    status_active_label: 'Active',
    status_disabled_label: 'Disabled',
  },
  hi: {
    brand_name: 'टास्कफ्लो',
    // Nav
    nav_dashboard: 'डैशबोर्ड',
    nav_team: 'टीम',
    nav_directives: 'निर्देश',
    nav_create_task: 'कार्य बनाएँ',
    nav_all_tasks: 'सभी कार्य',
    nav_all_users: 'सभी उपयोगकर्ता',
    nav_departments: 'विभाग',
    nav_analytics: 'एनालिटिक्स',
    nav_logout: 'लॉगआउट',
    nav_overview: 'अवलोकन',
    user_mgmt_tab: 'उपयोगकर्ता प्रबंधन',
    nav_features: 'विशेषताएं',
    nav_benefits: 'लाभ',
    nav_sys_status: 'सिस्टम स्थिति',
    nav_privacy: 'गोपनीयता',
    nav_terms: 'नियम',
    
    // Dashboard / Titles
    title_manager_hub: 'मैनेजर हब',
    title_control_center: 'कंट्रोल सेंटर',
    title_my_tasks: 'मेरे कार्य',
    title_overview: 'अवलोकन',
    system_control: 'सिस्टम नियंत्रण',
    root_access: 'रूट एक्सेस अधिकृत',
    global_metrics: 'वैश्विक मेट्रिक्स और नियंत्रण',
    landing_hero_title: 'कुलीन संगठनों के लिए ',
    landing_hero_highlight: 'उत्कृष्ट निष्पादन।',
    landing_hero_subtitle: 'बिखरे हुए संचार को व्यवस्थित, उच्च-वेग वाले कार्य जीवनचक्र प्रबंधन में बदलें।',
    landing_signin_btn: 'वर्कस्पेस में साइन इन करें',
    landing_docs_btn: 'दस्तावेज़ देखें',
    feature_title: 'सटीकता के साथ इंजीनियर किया गया',
    feature_subtitle: 'आपके वर्कफ़्लो से घर्षण को दूर करने के लिए बनाया गया हर फीचर।',
    access_workspace: 'वर्कस्पेस एक्सेस करें',
    sys_ops_os: 'एंटरप्राइज ऑपरेशंस ओएस v2.4',
    
    // Stats
    stat_active: 'सक्रिय',
    stat_pending: 'लंबित',
    stat_completed: 'पूरा हुआ',
    stat_overdue: 'विलंबित',
    stat_total_tasks: 'कुल कार्य',
    stat_active_cycles: 'सक्रिय चक्र',
    stat_pending_queue: 'लंबित कतार',
    stat_critical_overdue: 'गंभीर विलंब',
    stat_total: 'कुल',
    
    // Task Card & Tables
    task_priority: 'प्राथमिकता',
    task_status: 'स्थिति',
    task_due_date: 'नियत तारीख',
    task_assigned_to: 'सौपा गया',
    task_department: 'विभाग',
    task_edit: 'संपादन',
    task_transfer: 'ट्रांसफर',
    task_directive_label: 'कार्य निर्देश',
    assignee_label: 'सौंपने वाला',
    level_label: 'स्तर',
    actions_label: 'कार्यवाही',
    records_label: 'रिकॉर्ड',
    user_label: 'उपयोगकर्ता',
    role_label: 'भूमिका',
    nav_status: 'स्थिती',
    
    // Priorities
    priority_low: 'कम',
    priority_med: 'मध्यम',
    priority_high: 'उच्च',
    
    // Statuses
    status_pending: 'लंबित',
    status_active: 'प्रगति में',
    status_done: 'पूरा',
    online_status: 'ऑनलाइन',
    revoked_status: 'निरस्त',
    
    // Common Buttons
    btn_cancel: 'कैंसिल',
    btn_create: 'बनाएँ',
    btn_assign: 'सौंपें',
    btn_reset: 'रीसेट',
    btn_delete: 'डिलीट',
    btn_confirm: 'पुष्टि करें',
    btn_abort: 'रद्द करें',
    btn_proceed: 'आगे बढ़ें',
    btn_save: 'सहेजें',
    btn_revoke: 'वापस लें',
    btn_grant: 'अनुदान दें',
    btn_view_tasks: 'कार्य देखें',
    btn_transfer: 'ट्रांसफर',
    btn_add_employee: 'एम्प्लोई जोड़ें',
    btn_deploy_task: 'टास्क तैनात करें',
    btn_initiate: 'शुरू करें',
    btn_initialize: 'कनेक्शन शुरू करें',
    btn_login: 'लॉगिन',
    btn_create_user: 'यूजर बनाएँ',
    btn_assign_task: 'टास्क सौंपें',
    btn_transmit: 'ट्रांसमिट',
    btn_purge: 'टास्क मिटाएं',
    btn_update: 'अपडेट हो रहा है...',
    btn_creating: 'बनाया जा रहा है...',
    
    // Placeholders & Search
    ph_search_name: 'नाम या ईमेल से खोजें...',
    ph_enter_dept: 'विभाग का नाम दर्ज करें...',
    ph_task_title: 'कार्य का शीर्षक...',
    ph_task_desc: 'मिशन विवरण...',
    ph_full_name: 'पूरा नाम',
    ph_email: 'ईमेल पता',
    ph_password: 'पासवर्ड',
    ph_new_password: 'नया पासवर्ड',
    ph_confirm_password: 'पासवर्ड की पुष्टि करें',
    ph_search_directives: 'निर्देश खोजें...',
    ph_mission_details: 'मिशन विगतेलों...',
    ph_sys_update: 'सिस्टम अपडेट...',
    ph_search_user: 'यूजर खोजें...',
    ph_brief_description: 'संक्षिप्त विवरण (वैकल्पिक)',
    ph_select_manager: 'मैनेजर चुनें...',
    ph_select_dept: 'विभाग चुनें...',
    ph_admin_token: 'टर्मिनल एक्सेस के लिए आवश्यक',
    
    // Messages & Alerts
    msg_loading: 'लोड हो रहा है...',
    msg_no_tasks: 'कोई निर्देश नहीं मिला',
    msg_no_tasks_found: 'कोई कार्य नहीं मिला',
    msg_tasks_appear_here: 'कार्य यहाँ दिखाई देंगे।',
    msg_task_update_success: 'कार्य को {status} के रूप में चिह्नित किया गया है',
    msg_task_updated: 'कार्य सफलतापूर्वक अपडेट किया गया',
    msg_failed_update: 'कार्य अपडेट करने में विफल',
    msg_title_required: 'शीर्षक आवश्यक है',
    msg_assignee_required: 'सौंपने वाला व्यक्ति आवश्यक है',
    msg_no_users: 'कोई उपयोगकर्ता नहीं मिला',
    msg_no_notifs: 'अभी तक कोई नोटिफिकेशन नहीं है।',
    msg_no_results: 'कोई रिकॉर्ड नहीं मिला',
    msg_updating: 'अपडेट हो रहा है...',
    overdue_alert: 'विलंब अलर्ट',
    mission_progress: 'मिशन प्रगति',
    all_tasks_on_schedule: 'सभी कार्य समय पर हैं',
    overdue_tasks_alert: 'विलंबित कार्यों पर तत्काल ध्यान दें',
    msg_unassigned: 'अनिर्धारित',
    msg_no_employees_found: 'कोई कर्मचारी नहीं मिला',
    msg_no_employees_desc: 'दूसरा नाम या ईमेल आज़माएं, या नया कर्मचारी जोड़ें।',
    
    // Departments
    dept_hr: 'एचआर',
    dept_it: 'आईटी',
    dept_sales: 'बिक्री',
    dept_design: 'डिजाइन',
    dept_marketing: 'मार्केटिंग',
    dept_development: 'विकास',
    dept_comp_rates: 'विभाग पूर्णता दर',
    create_dept_title: 'विभाग बनाएँ',
    active_depts: 'सक्रिय विभाग',
    all_depts_filter: 'सभी विभाग',
    
    // Roles
    role_manager: 'मैनेजर',
    role_employee: 'एम्प्लोई',
    role_admin: 'एडमिन',
    label_managers: 'मैनेजर',
    label_employees: 'एम्प्लोई',
    label_admins: 'एडमिन',
    role_selector_title: 'भूमिका चुनें',
    
    // Manager Specific
    all_depts: 'सभी विभाग',
    cross_dept_cmd: 'क्रॉस-डिपार्टमेंट कमांड',
    dept_mgr_dir: 'विभाग प्रबंधन निर्देशिका',
    cmd_roster: 'टीम रोस्टर',
    hide_tfr_list: 'ट्रांसफर सूची छिपाएं',
    open_tfr_list: 'ट्रांसफर सूची खोलें',
    tfr_task_ready: 'कार्य स्थानांतरण के लिए तैयार',
    label_mgr_overview: 'अवलोकन',
    tfr_incoming: 'आने वाला',
    tfr_sent: 'भेजा गया',
    tfr_task_list: 'ट्रांसफर टास्क लिस्ट',
    tfr_directives: 'स्थानांतरित निर्देश',
    tfr_from: 'भेजने वाला मैनेजर',
    tfr_to: 'प्राप्तकर्ता मैनेजर',
    tfr_timestamp: 'स्थानांतरित समय',
    target_dept: 'लक्ष्य विभाग',
    target_manager: 'लक्ष्य मैनेजर',
    receiving_manager: 'प्राप्तकर्ता मैनेजर',
    
    // Admin Specific
    title_create_user: 'नया यूजर बनाएँ',
    title_assign_task: 'नया कार्य सौंपें',
    title_reset_password: 'पासवर्ड रीसेट करें',
    title_delete_dept: 'विभाग डिलीट करें?',
    title_sys_auth: 'सिस्टम प्राधिकरण आवश्यक',
    auth_final: 'अंतिम प्राधिकरण',
    detected_conflicts: 'पाए गए विसंगतियां',
    irrevocable_action: 'गंभीर: यह क्रिया अपरिवर्तनीय है।',
    label_users: 'यूजर',
    label_active_count: 'सक्रिय',
    dept_workload: 'डिपार्टमेंट वर्कलोड',
    status_split: 'ग्लोबल स्टेटस स्प्लिट',
    
    // Login & Onboarding
    identify_clearance: 'लॉगिन क्लीयरेंस पहचानें',
    sector_command: 'सेक्टर कमांड',
    workspace_access: 'वर्कस्पेस एक्सेस',
    op_terminal_login: 'ऑपरेशनल टर्मिनल लॉगिन',
    onboarding_title: 'सुरक्षित ऑनबोर्डिंग',
    onboarding_subtitle: 'सक्रियण',
    set_passphrase: 'पासफ़्रेज़ सेट करें',
    activate_btn: 'खाता सक्रिय करें',
    account_activated: 'खाता सक्रिय हुआ',
    login_proceed: 'लॉगिन करें',
    val_invite: 'आमंत्रण की पुष्टि हो रही है...',
    link_expired: 'लिंक समाप्त हो गया',
    already_activated: 'पहले से सक्रिय',
    onboarding_footer: 'यह एक सुरक्षित सक्रियण लिंक है। इसे साझा न करें।',
    login_email: 'ईमेल',
    login_password: 'पासवर्ड',
    back_to_root: 'रूट पर वापस जाएं',
    initiate_btn: 'आरंभ करें',
    admin_workspace: 'एडमिन कमांड सेंटर',
    manager_workspace: 'मैनेजर सेक्टर नियंत्रण',
    employee_workspace: 'एम्प्लोई वर्कस्पेस एक्सेस',
    sys_decrypt_token: 'सिस्टम डिक्रिप्ट टोकन',
    auth_prohibited: 'अनधिकृत पहुंच सख्त वर्जित है।',
    auth_logged: 'सभी ऑपरेशन लॉग किए जाते हैं।',
    init_conn_btn: 'लॉगिन',
    title_manager_hub: 'प्रबंधक हब',
    title_manager_overview: 'अवलोकन',
    
    // Signup
    title_create_account: 'खाता बनाएं',
    subtitle_join_today: 'आज ही टास्कफ्लो से जुड़ें',
    label_full_name: 'पूरा नाम',
    ph_john_doe: 'जॉन डो',
    ph_example_email: 'you@example.com',
    msg_already_have_account: 'क्या आपके पास पहले से खाता है?',
    link_signin: 'साइन इन करें',
    btn_create_account: 'खाता बनाएं',
    
    // Feature Details
    feature_1_title: 'मिलिट्री-ग्रेड एक्सेस कंट्रोल',
    feature_1_desc: 'कोई सार्वजनिक साइनअप नहीं। सख्त पदानुक्रमित प्रावधान।',
    feature_2_title: 'रियल-टाइम सिंक्रोनाइज़ेशन',
    feature_2_desc: 'वेबसॉकेट्स द्वारा संचालित। तत्काल कार्य तैनाती।',
    feature_3_title: 'स्वचालित जीवनचक्र',
    feature_3_desc: 'स्वायत्त डेटाबेस क्लीनअप रूटीन।',
    feature_4_title: 'सेक्टर अलगाव',
    feature_4_desc: 'JSON-आधारित गतिशील विभाग रूटिंग।',
    
    // Testimonials & Footer
    trusted_by: 'गति-प्रेमी टीमों द्वारा विश्वसनीय।',
    testimonial_1_text: "टास्कफ्लो ने 5 अलग-अलग उपकरणों पर हमारी निर्भरता को समाप्त कर दिया। संरचनात्मक कठोरता ने वास्तव में हमें 3 गुना तेजी से आगे बढ़ाया।",
    testimonial_1_author: "सारा जेनकिंस",
    testimonial_1_role: "वीपी इंजीनियरिंग, नेक्ससटेक",
    testimonial_2_text: "प्रोजेक्ट मैनेजमेंट के लिए मैंने अब तक का सबसे साफ यूआई देखा है। यह मेरे मस्तिष्क के विस्तार जैसा लगता है।",
    testimonial_2_author: "मार्कस थोर्न",
    testimonial_2_role: "प्रोडक्ट लीड, सिंथेटिक्स",
    testimonial_3_text: "हमें भारी-भरकम इंटरफेस के बिना सख्त पदानुक्रमित नियंत्रण की आवश्यकता थी। इसने इसे पूरी तरह से वितरित किया।",
    testimonial_3_author: "एलेना रोड्रिगेज",
    testimonial_3_role: "संचालन निदेशक, वॉयडकॉर्प",
    cta_title: 'क्या आप अपने वर्कफ़्लो को विकसित करने के लिए तैयार हैं?',
    cta_subtitle: 'पहुंच आमंत्रित कर्मियों तक सीमित है।',
    cta_btn: 'टास्कफ्लो में प्रवेश करें',
    footer_rights: '© 2026 टास्कफ्लो सिस्टम्स इंक। सर्वाधिकार सुरक्षित।',
    tag_overdue: 'विलंब',
    tag_due: 'बाकी',
    tag_left: 'बचा है',
    tag_ovr: 'OVR',
    tooltip_edit: 'निर्देश संपादित करें',
    task_transfer_btn: 'ट्रांसफर',
    activated_desc: 'आपका खाता सफलतापूर्वक सक्रिय हो गया है। अब आप ऑपरेशनल टर्मिनल तक पहुँच सकते हैं।',
    go_to_login: 'लॉगिन पर जाएं',
    val_invite_err: 'अमान्य या समाप्त हो चुका आमंत्रण लिंक।',
    activate_err: 'खाता सक्रिय करने में विफल।',
    invalid_invite: 'अमान्य आमंत्रण।',
    access_denied: 'पहुंच वर्जित',
    passphrase_min_len: 'पासफ़्रेज़ कम से कम 6 अक्षरों का होना चाहिए।',
    passphrase_mismatch: 'पासवर्ड मेल नहीं खाते।',
    
    // Error States
    err_failed_depts: 'विभाग लोड करने में विफल',
    err_failed_users: 'यूजर लोड करने में विफल',
    err_failed_history: 'टास्क इतिहास प्राप्त करने में विफल।',
    err_pass_mismatch: 'पासवर्ड मेल नहीं खाते।',
    err_pass_short: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
    err_name_req: 'विभाग का नाम आवश्यक है।',
    err_select_manager: 'एम्प्लोई के लिए एक मैनेजर चुनें।',
    msg_tfr_params_err: 'ट्रांसफर के लिए टास्क, विभाग और मैनेजर चुनें।',

    // Additional Dashboard Keys
    dept_mgr_desc: 'प्रत्येक विभाग प्रबंधक को देखें और दूसरे मैनेजर को निर्देश सौंपें।',
    loading_mgr_net: 'विभाग मैनेजर नेटवर्क लोड हो रहा है...',
    label_department: 'विभाग',
    label_transferred: 'स्थानांतरित',
    msg_no_mgr_mapping: 'कोई विभाग मैनेजर मैपिंग उपलब्ध नहीं है।',
    msg_tfr_desc: 'मैनेजरों के बीच स्थानांतरित किए गए कार्य स्रोत और गंतव्य मैनेजर विवरण के साथ यहां दिखाई देते हैं।',
    label_tfr_record: 'ट्रांसफर रिकॉर्ड',
    label_tfr_records: 'ट्रांसफर रिकॉर्ड',
    label_assigned_ems: 'सौंपे गए कर्मचारी',
    label_assigned_ems_desc: 'केवल आपके खाते में सौंपे गए कर्मचारी ही यहां दिखाए गए हैं।',
    ph_search_ems: 'नाम या ईमेल द्वारा कर्मचारी खोजें...',
    btn_add_emp: 'एम्प्लोई जोड़ें',
    label_total_emp: 'कुल कर्मचारी',
    label_total_emps: 'कुल कर्मचारी',
    label_visible: 'दृश्यमान',
    btn_disable_emp: 'एम्प्लोई को अक्षम करें',
    btn_enable_emp: 'एम्प्लोई को सक्षम करें',
    msg_no_ems_found: 'कोई कर्मचारी नहीं मिला',
    msg_no_ems_found_desc: 'दूसरा नाम या ईमेल आज़माएं, या नया कर्मचारी जोड़ें।',
    msg_no_tasks_criteria: 'वर्तमान मानदंडों से मेल खाने वाला कोई निर्देश नहीं है',
    label_records_caps: 'रिकॉर्ड',
    msg_no_tasks_dept: 'इस विभाग में कोई निर्देश नहीं है',
    label_regional_cmd: 'क्षेत्रीय कमांड अधिकृत',
    label_mgr_overview: 'मैनेजर अवलोकन',
    msg_managing_intro: 'आप प्रबंधित कर रहे हैं',
    msg_managing_dept: 'विभाग',
    msg_managing_depts: 'विभागों',
    label_managing_depts: 'प्रबंध विभाग',
    btn_deploy_task_caps: 'टास्क तैनात करें',
    tab_overview: 'अवलोकन',
    tab_team: 'टीम',
    tab_tasks: 'टास्क',

    // Modals & Forms
    title_deploy_directive: 'नया निर्देश तैनात करें',
    title_edit_directive: 'कार्य निर्देश संपादित करें',
    label_directive_desig: '// निर्देश पदनाम',
    ph_example_directive: 'जैसे: सबसिस्टम अल्फा शुरू करें',
    label_parameters_opt: '// पैरामीटर (वैकल्पिक)',
    label_assign_emp: '// कर्मचारी सौंपें',
    ph_search_name_email: 'नाम या ईमेल खोजें',
    label_target_dept: '// लक्ष्य विभाग',
    label_start_cycle: '// प्रारंभ चक्र',
    label_deadline_cycle: '// समय सीमा चक्र',
    label_priority_level: '// प्राथमिकता स्तर',
    btn_transmit_caps: '⚡ ट्रांसमिट',
    title_create_emp: 'नया कर्मचारी बनाएँ',
    label_full_name_caps: '// पूरा नाम',
    label_email_caps: '// ईमेल',
    label_password_caps: '// पासवर्ड',
    ph_min_6_char: 'न्यूनतम 6 अक्षर',
    label_assign_dept_caps: '// विभाग सौंपें',
    msg_select_dept_err: '⚠ एक विभाग चुनें',
    btn_create_emp_caps: '⚡ कर्मचारी बनाएँ',
    title_tfr_directive: 'मैनेजर को निर्देश स्थानांतरित करें',
    label_selected_task: 'चयनित कार्य',
    msg_select_task_queue: 'अपनी कतार से एक कार्य चुनें',
    msg_curr_dept_status: 'वर्तमान विभाग: {dept} | वर्तमान स्थिति: {status}',
    msg_tfr_instruction: 'एक निर्देश चुनें जो दूसरे विभाग मैनेजर के पास जाना चाहिए।',
    msg_no_tfr_ready: 'अभी आपकी कतार में कोई ट्रांसफर-तैयार कार्य नहीं मिला। केवल आपके प्रबंधित विभागों के भीतर आपके स्वामित्व वाले कार्य ही स्थानांतरित किए जा सकते हैं।',
    msg_no_mgr_avail: 'फिलहाल ट्रांसफर के लिए कोई अन्य सक्रिय मैनेजर उपलब्ध नहीं है। इस कार्य को स्थानांतरित करने के लिए किसी विभाग में एक अन्य सक्रिय मैनेजर जोड़ें।',
    label_choose_task: '// कार्य चुनें',
    ph_select_task: '-- कार्य चुनें --',
    label_target_mgr: '// लक्ष्य मैनेजर',
    ph_select_mgr: '-- मैनेजर चुनें --',
    msg_no_mgr_dept: 'चयनित विभाग के भीतर कोई अन्य सक्रिय मैनेजर उपलब्ध नहीं है।',
    label_receiving_mgr: 'प्राप्तकर्ता मैनेजर',
    label_depts_list: 'विभाग:',
    btn_transfer_caps: 'कार्य स्थानांतरित करें',
    btn_transferring: 'स्थानांतरित हो रहा है...',

    // Admin Specific
    title_user_tasks: '// सौंपे गए कार्य',
    msg_no_tasks_assigned: 'कोई कार्य नहीं सौंपा गया',
    label_due: 'नियत तारीख:',
    label_user_role: '// भूमिका चुनें',
    label_assign_mgr: '// मैनेजर सौंपें',
    ph_search_role_email: 'नाम या ईमेल से खोजें',
    label_task_title: '// कार्य शीर्षक',
    ph_task_title_placeholder: 'कार्य शीर्षक',
    label_priority: '// प्राथमिकता',
    label_target_user: 'लक्ष्य यूजर',
    msg_reset_pass_desc: 'मौजूदा पासवर्ड कभी नहीं दिखाया जाता है। केवल एक नया पासवर्ड सेट किया जा सकता है।',
    ph_reenter_pass: 'नया पासवर्ड फिर से दर्ज करें',
    label_conflicts: '// पाए गए विसंगतियां:',
    label_emp_accounts: 'एम्प्लोई खाता(एं)',
    label_mgr_accounts: 'मैनेजर खाता(एं)',
    label_active_tasks: 'सक्रिय कार्य',
    btn_bypass_delete: 'बायपास और डिलीट',
    btn_confirm_delete: 'डिलीट की पुष्टि करें',

    // Greetings & Alerts
    welcome_back: 'आपका स्वागत है',
    hello: 'नमस्ते',
    sys_date: 'सिस्टम तिथि',
    all_priorities: 'सभी प्राथमिकताएं',
    critical_overdue: 'गंभीर विलंब',
    today_due: 'आज नियत',
    upcoming_queued: 'आगामी कतारबद्ध',
    completed_editable: 'पूरा (संपादन योग्य)',

    // Notifications
    notif_log: 'नोटिफिकेशन लॉग',
    task_alerts: 'टास्क अलर्ट',
    mark_read: 'सभी को पढ़ा हुआ मान लें',
    just_now: 'अभी-अभी',
    msg_no_notifs: 'अभी तक कोई नोटिफिकेशन नहीं है।',

    // Sidebar & Badges
    badge_employee: 'एम्प्लोई',
    badge_manager: 'मैनेजर',
    badge_admin: 'एडमिन',
    label_cyber_edition: 'साइबर एडिशन',
    label_dept_manager_caps: 'विभाग प्रबंधक',
    label_dept_manager: 'विभाग प्रबंधक',
    label_operator: 'ऑपरेटर',
    unassigned_caps: 'अनिर्धारित',
    all_statuses: 'सभी स्थितियाँ',
    all_employees: 'सभी एम्प्लोई',
    you: 'आप',
    status_active_label: 'सक्रिय',
    status_disabled_label: 'अक्षम',
  },
  gu: {
    brand_name: 'ટાસ્કફ્લો',
    // Nav
    nav_dashboard: 'ડેશબોર્ડ',
    nav_team: 'ટીમ',
    nav_directives: 'સૂચનાઓ',
    nav_create_task: 'કાર્ય બનાવો',
    nav_all_tasks: 'બધા કાર્યો',
    nav_all_users: 'બધા વપરાશકો',
    nav_departments: 'વિભાગો',
    nav_analytics: 'એનાલિટિક્સ',
    nav_logout: 'લોગઆઉટ',
    nav_overview: 'ઝાંખી',
    user_mgmt_tab: 'વપરાશકર્તા સંચાલન',
    nav_features: 'વિશેષતાઓ',
    nav_benefits: 'લાભ',
    nav_sys_status: 'સિસ્ટમ સ્થિતિ',
    nav_privacy: 'ગોપનીયતા',
    nav_terms: 'નિયમો',
    
    // Dashboard / Titles
    title_manager_hub: 'મેનેજર હબ',
    title_control_center: 'કંટ્રોલ સેન્ટર',
    title_my_tasks: 'મારા કાર્યો',
    title_overview: 'ઝાંખી',
    system_control: 'સિસ્ટમ નિયંત્રણ',
    root_access: 'રૂટ એક્સેસ અધિકૃત',
    global_metrics: 'વૈશ્વિક મેટ્રિક્સ અને નિયંત્રણ',
    landing_hero_title: 'કુલીન સંસ્થાઓ માટે ઉત્કૃષ્ટ પાલન.',
    landing_hero_subtitle: 'વિખરાયેલા સંવાદને વ્યવસ્થિત, ઉચ્ચ-વેગ ધરાવતા કાર્ય જીવનચક્ર સંચાલનમાં બદલો.',
    landing_signin_btn: 'વર્કસ્પેસમાં સાઇન ઇન કરો',
    landing_docs_btn: 'દસ્તાવેજો જુઓ',
    feature_title: 'ચોકસાઈ સાથે એન્જિનિયર્ડ',
    feature_subtitle: 'તમારા વર્કફ્લોમાંથી ઘર્ષણ દૂર કરવા માટે બનાવેલી દરેક વિશેષતા.',
    access_workspace: 'વર્કસ્પેસ એક્સેસ કરો',
    
    // Stats
    stat_active: 'સક્રિય',
    stat_pending: 'બાકી',
    stat_completed: 'પૂર્ણ',
    stat_overdue: 'મોડું',
    stat_total_tasks: 'કુલ કાર્યો',
    stat_active_cycles: 'સક્રિય ચક્ર',
    stat_pending_queue: 'બાકી કતાર',
    stat_critical_overdue: 'ગંભીર વિલંબ',
    stat_total: 'કુલ',
    
    // Task Card & Tables
    task_priority: 'પ્રાધાન્યતા',
    task_status: 'સ્થિતિ',
    task_due_date: 'નિયત તારીખ',
    task_assigned_to: 'સોંપેલ',
    task_department: 'વિભાગ',
    task_edit: 'સુધારો',
    task_transfer: 'ટ્રાન્સફર',
    task_directive_label: 'કાર્ય સૂચના',
    assignee_label: 'સોંપણી મેળવનાર',
    level_label: 'સ્તર',
    actions_label: 'ક્રિયાઓ',
    records_label: 'રેકોર્ડ્સ',
    user_label: 'વપરાશકર્તા',
    role_label: 'ભૂમિકા',
    nav_status: 'સ્થિતિ',
    
    // Priorities
    priority_low: 'ઓછી',
    priority_med: 'મધ્યમ',
    priority_high: 'ઉચ્ચ',
    
    // Statuses
    status_pending: 'બાકી',
    status_active: 'પ્રગતિમાં',
    status_done: 'પૂર્ણ',
    online_status: 'ઓનલાઈન',
    revoked_status: 'રદ કરેલ',
    
    // Common Buttons
    btn_cancel: 'કેન્સલ',
    btn_create: 'બનાવો',
    btn_assign: 'સોંપો',
    btn_reset: 'રીસેટ',
    btn_delete: 'ડીલીટ',
    btn_confirm: 'ખાતરી કરો',
    btn_abort: 'રદ કરો',
    btn_proceed: 'આગળ વધો',
    btn_save: 'સાચવો',
    btn_revoke: 'રદ કરો',
    btn_grant: 'મંજૂર કરો',
    btn_view_tasks: 'કાર્યો જુઓ',
    btn_transfer: 'ટ્રાન્સફર',
    btn_add_employee: 'એમ્પ્લોઈ ઉમેરો',
    btn_deploy_task: 'ટાસ્ક બનાવો',
    btn_initiate: 'શરૂ કરો',
    btn_initialize: 'કનેક્શન શરૂ કરો',
    btn_login: 'લોગિન',
    btn_create_user: 'યુઝર બનાવો',
    btn_assign_task: 'ટાસ્ક સોંપો',
    btn_transmit: 'ટ્રાન્સમિટ',
    btn_purge: 'ટાસ્ક કાઢી નાખો',
    btn_update: 'અપડેટ થઈ રહ્યું છે...',
    btn_creating: 'બનાવી રહ્યા છીએ...',
    
    // Placeholders & Search
    ph_search_name: 'નામ અથવા ઈમેલથી શોધો...',
    ph_enter_dept: 'વિભાગનું નામ લખો...',
    ph_task_title: 'કાર્યનું શીર્ષક...',
    ph_task_desc: 'મિશન વિગતો...',
    ph_full_name: 'પૂરું નામ',
    ph_email: 'ઈમેલ એડ્રેસ',
    ph_password: 'પાસવર્ડ',
    ph_new_password: 'નવો પાસવર્ડ',
    ph_confirm_password: 'પાસવર્ડની ખાતરી કરો',
    ph_search_directives: 'સૂચનાઓ શોધો...',
    ph_mission_details: 'મિશન વિગતો...',
    ph_sys_update: 'સિસ્ટમ અપડેટ...',
    ph_search_user: 'વપરાશકર્તા શોધો...',
    ph_brief_description: 'ટૂંકું વર્ણન (વૈકલ્પિક)',
    ph_select_manager: 'મેનેજર પસંદ કરો...',
    ph_select_dept: 'વિભાગ પસંદ કરો...',
    ph_admin_token: 'ટર્મિનલ એક્સેસ માટે જરૂરી',
    
    // Messages & Alerts
    msg_loading: 'લોડ થઈ રહ્યું છે...',
    msg_no_tasks: 'કોઈ સૂચના મળી નથી',
    msg_no_tasks_found: 'કોઈ કાર્યો મળ્યા નથી',
    msg_tasks_appear_here: 'કાર્યો અહીં દેખાશે.',
    msg_task_update_success: 'કાર્યને {status} તરીકે ચિહ્નિત કરવામાં આવ્યું છે',
    msg_task_updated: 'કાર્ય સફળતાપૂર્વક અપડેટ થયું',
    msg_failed_update: 'કાર્ય અપડેટ કરવામાં નિષ્ફળ',
    msg_title_required: 'શીર્ષક જરૂરી છે',
    msg_assignee_required: 'સોંપનાર વ્યક્તિ જરૂરી છે',
    msg_no_users: 'કોઈ વપરાશકર્તા મળ્યા નથી',
    msg_no_notifs: 'હજી સુધી કોઈ સૂચના નથી.',
    msg_no_results: 'કોઈ રેકોર્ડ મળ્યા નથી',
    msg_updating: 'અપડેટ થઈ રહ્યું છે...',
    overdue_alert: 'વિલંબ એલર્ટ',
    mission_progress: 'મિશન પ્રગતિ',
    all_tasks_on_schedule: 'બધા કાર્યો સમયસર છે',
    overdue_tasks_alert: 'વિલંબિત કાર્યો પર તરત ધ્યાન આપો',
    msg_unassigned: 'સોંપેલ નથી',
    msg_no_employees_found: 'કોઈ કર્મચારી મળ્યા નથી',
    msg_no_employees_desc: 'બીજું નામ અથવા ઈમેલ અજમાવો, અથવા નવો કર્મચારી ઉમેરો.',
    
    // Departments
    dept_hr: 'એચઆર',
    dept_it: 'આઈટી',
    dept_sales: 'વેચાણ',
    dept_design: 'ડિઝાઇન',
    dept_marketing: 'માર્કેટિંગ',
    dept_development: 'વિકાસ',
    dept_comp_rates: 'વિભાગ પૂર્ણતા દર',
    create_dept_title: 'વિભાગ બનાવો',
    active_depts: 'સક્રિય વિભાગો',
    all_depts_filter: 'બધા વિભાગો',
    
    // Roles
    role_manager: 'મેનેજર',
    role_employee: 'એમ્પ્લોઈ',
    role_admin: 'એડમિન',
    label_managers: 'મેનેજર',
    label_employees: 'એમ્પ્લોઈ',
    label_admins: 'એડમિન',
    role_selector_title: 'ભૂમિકા પસંદ કરો',
    
    // Manager Specific
    all_depts: 'બધા વિભાગો',
    cross_dept_cmd: 'ક્રોસ-ડિપાર્ટમેન્ટ કમાન્ડ',
    dept_mgr_dir: 'વિભાગ મેનેજર ડિરેક્ટરી',
    cmd_roster: 'કમાન્ડ રોસ્ટર',
    hide_tfr_list: 'ટ્રાન્સફર લિસ્ટ છુપાવો',
    open_tfr_list: 'ટ્રાન્સફર લિસ્ટ ખોલો',
    tfr_task_ready: 'ટ્રાન્સફર માટે તૈયાર કાર્યો',
    tfr_incoming: 'આવતું',
    tfr_sent: 'મોકલેલ',
    tfr_task_list: 'ટ્રાન્સફર ટાસ્ક લિસ્ટ',
    tfr_directives: 'તબદીલ કરાયેલ સૂચનાઓ',
    tfr_from: 'મોકલનાર મેનેજર',
    tfr_to: 'મેળવનાર મેનેજર',
    tfr_timestamp: 'સ્થાનાંતરિત સમય',
    target_dept: 'લક્ષ્ય વિભાગ',
    target_manager: 'લક્ષ્ય મેનેજર',
    receiving_manager: 'મેળવનાર મેનેજર',
    
    // Admin Specific
    title_create_user: 'નવો યુઝર બનાવો',
    title_assign_task: 'નવું કાર્ય સોંપો',
    title_reset_password: 'પાસવર્ડ રીસેટ કરો',
    title_delete_dept: 'વિભાગ ડીલીટ કરો?',
    title_sys_auth: 'સિસ્ટમ અધિકૃતતા જરૂરી',
    auth_final: 'અંતિમ અધિકૃતતા',
    detected_conflicts: 'શોધાયેલ વિવાદો',
    irrevocable_action: 'ગંભીર: આ ક્રિયા પાછી ખેંચી શકાશે નહીં.',
    label_users: 'યુઝર',
    label_active_count: 'સક્રિય',
    dept_workload: 'ડિપાર્ટમેન્ટ વર્કલોડ',
    status_split: 'ગ્લોબલ સ્ટેટસ સ્પ્લિટ',
    
    // Login & Onboarding
    identify_clearance: 'લોગિન ક્લિયરન્સ ઓળખો',
    sector_command: 'સેક્ટર કમાન્ડ',
    workspace_access: 'વર્કસ્પેસ એક્સેસ',
    op_terminal_login: 'ઓપરેશનલ ટર્મિનલ લોગિન',
    onboarding_title: 'સુરક્ષિત ઓનબોર્ડિંગ',
    onboarding_subtitle: 'સક્રિયકરણ',
    set_passphrase: 'પાસફ્રેઝ સેટ કરો',
    activate_btn: 'ખાતું સક્રિય કરો',
    account_activated: 'ખાતું સક્રિય થયું',
    login_proceed: 'લોગિન કરો',
    val_invite: 'આમંત્રણની ચકાસણી થઈ રહી છે...',
    link_expired: 'લિંક સમાપ્ત થઈ ગઈ',
    already_activated: 'પહેલેથી સક્રિય',
    onboarding_footer: 'આ સુરક્ષિત સક્રિયકરણ લિંક છે. તેને શેર કરશો નહીં.',
    login_email: 'ઈમેલ',
    login_password: 'પાસવર્ડ',
    back_to_root: 'રૂટ પર પાછા ફરો',
    initiate_btn: 'શરૂ કરો',
    admin_workspace: 'એડમિન કમાન્ડ સેન્ટર',
    manager_workspace: 'મેનેજર સેક્ટર નિયંત્રણ',
    employee_workspace: 'એમ્પ્લોઈ વર્કસ્પેસ એક્સેસ',
    sys_decrypt_token: 'સિસ્ટમ ડિક્રિપ્ટ ટોકન',
    auth_prohibited: 'અનધિકૃત એક્સેસ સખત પ્રતિબંધિત છે.',
    auth_logged: 'બધી કામગીરી લોગ કરવામાં આવે છે.',
    init_conn_btn: 'કનેક્શન શરૂ કરો',
    
    // Signup
    title_create_account: 'ખાતું બનાવો',
    subtitle_join_today: 'આજે જ ટાસ્કફ્લોમાં જોડાઓ',
    label_full_name: 'પૂરું નામ',
    ph_john_doe: 'જ્હોન ડો',
    ph_example_email: 'you@example.com',
    msg_already_have_account: 'શું તમારી પાસે પહેલેથી ખાતું છે?',
    link_signin: 'સાઇન ઇન કરો',
    btn_create_account: 'ખાતું બનાવો',
    
    // Feature Details
    feature_1_title: 'મિલિટરી-ગ્રેડ એક્સેસ કંટ્રોલ',
    feature_1_desc: 'કોઈ જાહેર સાઇનઅપ નથી. સખત વંશવેલો જોગવાઈ.',
    feature_2_title: 'રીઅલ-ટાઇમ સિંક્રનાઇઝેશન',
    feature_2_desc: 'વેબસૉકેટ્સ દ્વારા સંચાલિત. ઝટપટ કાર્ય જમાવટ.',
    feature_3_title: 'સ્વયંસંચાલિત જીવનચક્ર',
    feature_3_desc: 'સ્વાયત્ત ડેટાબેઝ સફાઈ દિનચર્યાઓ.',
    feature_4_title: 'સેક્ટર અલગતા',
    feature_4_desc: 'JSON-આધારિત ગતિશીલ વિભાગ રૂટિંગ.',
    
    // Testimonials & Footer
    trusted_by: 'વેગ-નબળી ટીમો દ્વારા વિશ્વસનીય.',
    testimonial_1_text: "ટાસ્કફ્લોએ 5 અલગ-અલગ ટૂલ્સ પરની અમારી નિર્ભરતાને દૂર કરી. માળખાકીય કઠોરતાએ ખરેખર અમને 3 ગણી ઝડપથી આગળ વધાર્યા.",
    testimonial_1_author: "સારા જેનકિન્સ",
    testimonial_1_role: "વીપી એન્જિનિયરિંગ, નેક્સસટેક",
    testimonial_2_text: "પ્રોજેક્ટ મેનેજમેન્ટ માટે મેં અત્યાર સુધીની સૌથી સ્વચ્છ UI જોઈ છે. તે મારા મગજનું વિસ્તરણ હોય તેવું લાગે છે.",
    testimonial_2_author: "માર્કસ થોર્ન",
    testimonial_2_role: "પ્રોડક્ટ લીડ, સિન્થેટિક્સ",
    testimonial_3_text: "અમને ભારે ઇન્ટરફેસ વગર સખત વંશવેલો નિયંત્રણની જરૂર હતી. આણે તે સંપૂર્ણ રીતે આપ્યું.",
    testimonial_3_author: "એલેના રોડ્રિગ્ઝ",
    testimonial_3_role: "ઓપરેશન્સ ડિરેક્ટર, વોઈડકોર્પ",
    cta_title: 'શું તમે તમારા વર્કફ્લોને વિકસિત કરવા માટે તૈયાર છો?',
    cta_subtitle: 'એક્સેસ આમંત્રિત કર્મચારીઓ સુધી મર્યાદિત છે.',
    cta_btn: 'ટાસ્કફ્લોમાં પ્રવેશ કરો',
    footer_rights: '© 2026 ટાસ્કફ્લો સિસ્ટમ્સ ઇન્ક. સર્વાધિકાર સુરક્ષિત.',
    tag_overdue: 'વિલંબ',
    tag_due: 'બાકી',
    tag_left: 'બાકી છે',
    tag_ovr: 'OVR',
    tooltip_edit: 'સૂચના સુધારો',
    task_transfer_btn: 'ટ્રાન્સફર',
    activated_desc: 'તમારું ખાતું સફળતાપૂર્વક સક્રિય થઈ ગયું છે. હવે તમે ઓપરેશનલ ટર્મિનલ એક્સેસ કરી શકો છો.',
    go_to_login: 'લોગિન પર જાઓ',
    val_invite_err: 'અમાન્ય અથવા સમાપ્ત થયેલ આમંત્રણ લિંક.',
    activate_err: 'ખાતું સક્રિય કરવામાં નિષ્ફળ.',
    invalid_invite: 'અમાન્ય આમંત્રણ.',
    access_denied: 'એક્સેસ નકારવામાં આવ્યો',
    passphrase_min_len: 'પાસફ્રેઝ ઓછામાં ઓછા 6 અક્ષરોનો હોવો જોઈએ.',
    passphrase_mismatch: 'પાસવર્ડ મેળ ખાતા નથી.',
    
    // Error States
    err_failed_depts: 'વિભાગો લોડ કરવામાં નિષ્ફળ',
    err_failed_users: 'યુઝર લોડ કરવામાં નિષ્ફળ',
    err_failed_history: 'યુઝર ટાસ્ક ઇતિહાસ મેળવવામાં નિષ્ફળ.',
    err_pass_mismatch: 'પાસવર્ડ મેળ ખાતા નથી.',
    err_pass_short: 'પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરોનો હોવો જોઈએ.',
    err_name_req: 'વિભાગનું નામ જરૂરી છે.',
    err_select_manager: 'એમ્પ્લોઈ માટે મેનેજર પસંદ કરો.',
    msg_tfr_params_err: 'ટ્રાન્સફર માટે ટાસ્ક, વિભાગ અને મેનેજર પસંદ કરો.',

    // Additional Dashboard Keys
    dept_mgr_desc: 'દરેક વિભાગના મેનેજરને જુઓ અને બીજા મેનેજરને સૂચના સોંપો.',
    loading_mgr_net: 'વિભાગ મેનેજર નેટવર્ક લોડ થઈ રહ્યું છે...',
    label_department: 'વિભાગ',
    label_transferred: 'સ્થાનાંતરિત',
    msg_no_mgr_mapping: 'કોઈ વિભાગ મેનેજર મેપિંગ ઉપલબ્ધ નથી.',
    msg_tfr_desc: 'મેનેજરો વચ્ચે ટ્રાન્સફર થયેલા કાર્યો સ્ત્રોત અને ગંતવ્ય મેનેજરની વિગતો સાથે અહીં દેખાય છે.',
    label_tfr_record: 'ટ્રાન્સફર રેકોર્ડ',
    label_tfr_records: 'ટ્રાન્સફર રેકોર્ડ્સ',
    label_assigned_ems: 'સોંપેલ કર્મચારીઓ',
    label_assigned_ems_desc: 'ફક્ત તમારા ખાતામાં સોંપેલ કર્મચારીઓ અહીં બતાવવામાં આવ્યા છે.',
    ph_search_ems: 'નામ અથવા ઈમેલ દ્વારા કર્મચારી શોધો...',
    btn_add_emp: 'એમ્પ્લોઈ ઉમેરો',
    label_total_emp: 'કુલ કર્મચારી',
    label_total_emps: 'કુલ કર્મચારીઓ',
    label_visible: 'દ્રશ્યમાન',
    btn_disable_emp: 'એમ્પ્લોઈને અક્ષમ કરો',
    btn_enable_emp: 'એમ્પ્લોઈને સક્ષમ કરો',
    msg_no_ems_found: 'કોઈ કર્મચારી મળ્યા નથી',
    msg_no_ems_found_desc: 'બીજું નામ અથવા ઈમેલ અજમાવો, અથવા નવો કર્મચારી ઉમેરો.',
    msg_no_tasks_criteria: 'વર્તમાન માપદંડો સાથે મેળ ખાતી કોઈ સૂચના નથી',
    label_records_caps: 'રેકોર્ડ્સ',
    msg_no_tasks_dept: 'આ વિભાગમાં કોઈ સૂચના નથી',
    label_regional_cmd: 'પ્રાદેશિક કમાન્ડ અધિકૃત',
    label_mgr_overview: 'મેનેજર વિહંગાવલોકન',
    msg_managing_intro: 'તમે સંચાલન કરી રહ્યા છો',
    msg_managing_dept: 'વિભાગ',
    msg_managing_depts: 'વિભાગો',
    label_managing_depts: 'મેનેજિંગ વિભાગો',
    btn_deploy_task_caps: 'ટાસ્ક બનાવો',
    tab_overview: 'ઝાંખી',
    tab_team: 'ટીમ',
    tab_tasks: 'ટાસ્ક',

    // Modals & Forms
    title_deploy_directive: 'નવો નિર્દેશ તૈનાત કરો',
    title_edit_directive: 'કાર્ય નિર્દેશ સંપાદિત કરો',
    label_directive_desig: '// સૂચના હોદ્દો',
    ph_example_directive: 'દા.ત. સબસિસ્ટમ આલ્ફા શરૂ કરો',
    label_parameters_opt: '// પરિમાણો (વૈકલ્પિક)',
    label_assign_emp: '// કર્મચારી સોંપો',
    ph_search_name_email: 'નામ અથવા ઈમેલ શોધો',
    label_target_dept: '// લક્ષ્ય વિભાગ',
    label_start_cycle: '// શરૂઆત ચક્ર',
    label_deadline_cycle: '// અંતિમ ચક્ર',
    label_priority_level: '// અગ્રતા સ્તર',
    btn_transmit_caps: '⚡ ટ્રાન્સમિટ',
    title_create_emp: 'નવો કર્મચારી બનાવો',
    label_full_name_caps: '// પૂરું નામ',
    label_email_caps: '// ઈમેલ',
    label_password_caps: '// પાસવર્ડ',
    ph_min_6_char: 'ન્યૂનતમ 6 અક્ષરો',
    label_assign_dept_caps: '// વિભાગ સોંપો',
    msg_select_dept_err: '⚠ વિભાગ પસંદ કરો',
    btn_create_emp_caps: '⚡ કર્મચારી બનાવો',
    title_tfr_directive: 'મેનેજરને સૂચના ટ્રાન્સફર કરો',
    label_selected_task: 'પસંદ કરેલ કાર્ય',
    msg_select_task_queue: 'તમારી કતારમાંથી એક કાર્ય પસંદ કરો',
    msg_curr_dept_status: 'વર્તમાન વિભાગ: {dept} | વર્તમાન સ્થિતિ: {status}',
    msg_tfr_instruction: 'બીજા વિભાગના મેનેજર પાસે મોકલવા માટે સૂચના પસંદ કરો.',
    msg_no_tfr_ready: 'અત્યારે તમારી કતારમાં કોઈ ટ્રાન્સફર-તૈયાર કાર્યો મળ્યા નથી. ફક્ત તમારા સંચાલિત વિભાગોની અંદર તમારી માલિકીના કાર્યો જ ટ્રાન્સફર કરી શકાય છે.',
    msg_no_mgr_avail: 'અત્યારે ટ્રાન્સફર માટે અન્ય કોઈ સક્રિય મેનેજર ઉપલબ્ધ નથી. આ કાર્યને ખસેડવા માટે વિભાગમાં અન્ય સક્રિય મેનેજર ઉમેરો.',
    label_choose_task: '// કાર્ય પસંદ કરો',
    ph_select_task: '-- કાર્ય પસંદ કરો --',
    label_target_mgr: '// લક્ષ્ય મેનેજર',
    ph_select_mgr: '-- મેનેજર પસંદ કરો --',
    msg_no_mgr_dept: 'પસંદ કરેલ વિભાગની અંદર અન્ય કોઈ સક્રિય મેનેજર ઉપલબ્ધ નથી.',
    label_receiving_mgr: 'મેળવનાર મેનેજર',
    label_depts_list: 'વિભાગો:',
    btn_transfer_caps: 'કાર્ય ટ્રાન્સફર કરો',
    btn_transferring: 'ટ્રાન્સફર થઈ રહ્યું છે...',

    // Admin Specific
    title_user_tasks: '// સોંપેલ કાર્યો',
    msg_no_tasks_assigned: 'કોઈ કાર્ય સોંપેલ નથી',
    label_due: 'નિયત તારીખ:',
    label_user_role: '// ભૂમિકા પસંદ કરો',
    label_assign_mgr: '// મેનેજર સોંપો',
    ph_search_role_email: 'નામ અથવા ઈમેલ દ્વારા શોધો',
    label_task_title: '// કાર્યનું શીર્ષક',
    ph_task_title_placeholder: 'કાર્યનું શીર્ષક',
    label_priority: '// અગ્રતા',
    label_target_user: 'લક્ષ્ય વપરાશકર્તા',
    msg_reset_pass_desc: 'હાલનો પાસવર્ડ ક્યારેય બતાવવામાં આવતો નથી. ફક્ત નવો પાસવર્ડ સેટ કરી શકાય છે.',
    ph_reenter_pass: 'નવો પાસવર્ડ ફરીથી લખો',
    label_conflicts: '// શોધાયેલ વિવાદો:',
    label_emp_accounts: 'એમ્પ્લોઈ ખાતું(ઓ)',
    label_mgr_accounts: 'મેનેજર ખાતું(ઓ)',
    label_active_tasks: 'સક્રિય કાર્યો',
    btn_bypass_delete: 'બાયપાસ અને ડીલીટ',
    btn_confirm_delete: 'ડીલીટની ખાતરી કરો',

    // Greetings & Alerts
    welcome_back: 'તમારું સ્વાગત છે',
    hello: 'નમસ્તે',
    sys_date: 'સિસ્ટમ તારીખ',
    all_priorities: 'બધી અગ્રતાઓ',
    critical_overdue: 'ગંભીર વિલંબ',
    today_due: 'આજે નિયત',
    upcoming_queued: 'આગામી કતારબદ્ધ',
    completed_editable: 'પૂર્ણ (સુધારી શકાય તેવું)',

    // Notifications
    notif_log: 'નોટિફિકેશન લોગ',
    task_alerts: 'ટાસ્ક એલર્ટ',
    mark_read: 'બધાને વંચાયેલ તરીકે માર્ક કરો',
    just_now: 'હમણાં જ',
    msg_no_notifs: 'હજી સુધી કોઈ સૂચના નથી.',

    // Sidebar & Badges
    badge_employee: 'એમ્પ્લોઈ',
    badge_manager: 'મેનેજર',
    badge_admin: 'એડમિન',
    label_cyber_edition: 'સાયબર એડિશન',
    label_dept_manager_caps: 'વિભાગ મેનેજર',
    label_dept_manager: 'વિભાગ મેનેજર',
    label_operator: 'ઓપરેટર',
    unassigned_caps: 'અનિયુક્ત',
    all_statuses: 'બધી સ્થિતિઓ',
    all_employees: 'બધા એમ્પ્લોઈ',
    you: 'તમે',
    status_active_label: 'સક્રિય',
    status_disabled_label: 'અક્ષમ',
  },
};

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState(localStorage.getItem('preferredLanguage') || 'en');

  useEffect(() => {
    localStorage.setItem('preferredLanguage', currentLanguage);
  }, [currentLanguage]);

  const t = (key) => {
    return translations[currentLanguage][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
